branch-defaults:
  default:
    environment: likelion-env
  master:
    environment: webeingfruits-env
environment-defaults:
  likelion-env:
    branch: null
    repository: null
global:
  application_name: django-tutorial
  default_ec2_keyname: aws-eb
  default_platform: Python 3.6
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: null
  workspace_type: Application
