# Generated by Django 3.1 on 2020-11-06 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_auto_20201020_2301'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurant',
            options={'ordering': ['name'], 'verbose_name': 'restaurant', 'verbose_name_plural': 'restaurants'},
        ),
    ]
